config/routes.rb
Rails.application.routes.draw do
  authenticated do
    resources :users, only: [:show] do
      resources :answers
    end
    resources :questions do
      resources :tags
      collection do
        get :answered
      end
      resources :answers do
        member do
          patch :select_answer
        end
      end
    end
    resources :tags
  end
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#welcome", as: :welcome
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_one :answered_question, class_name: "Question", foreign_key: 'selected_answer_id'
  validates_presence_of :answer, message: "Please include an answer."
  before_destroy :nullify_selected_answer

  private

  def nullify_selected_answer
    question = self.answered_question
    question.update(selected_answer_id: nil) if question
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :selected_answer, class_name: "Answer", optional: true
  has_many :answers, dependent: :destroy
  has_many :question_tags, autosave: true, dependent: :destroy
  has_many :tags, through: :question_tags

  validates_presence_of :content, message: "Empty questions are not virtuous"
  validates_presence_of :summary, message: "Brevity is the soul of wit, so summary is required"
  
  def self.search(query)
    distinct.left_outer_joins(:tags).where("summary LIKE :query OR content LIKE :query OR tags.name LIKE :query", query: "%#{query}%")
  end

  def self.answered
    where("selected_answer_id IS NOT NULL")
  end

  def question_tags_attributes=(attrs)
    # Mark any existing question tags for destruction, so they can be replaced by the freshly built tags on save
    self.question_tags.each(&:mark_for_destruction)

    # convert attrs hash to array of values, then look through array of tags submitted by the user
    # and remove the ones that have a blank color or tag name
    attrs.values.reject {|x| x["name"].blank? || x["color"].blank? }.each do |tag_color_hash|
      tag = Tag.find_or_initialize_by(name: tag_color_hash["name"])
      self.question_tags.build(tag: tag, color: tag_color_hash["color"])
    end
  end
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
  belongs_to :tag
  belongs_to :question
  delegate :name, to: :tag, allow_nil: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :question_tags
  has_many :questions, through: :question_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end

    user.update(image_url: auth.info.image, full_name: auth.info.name)
    user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    if params[:user_id]
      @answers = Answer.where(user_id: params[:user_id])
    else
      @answers = Answer.all
    end
  end

  def new
    @answer = Answer.new(question_id: params[:question_id])
    @question = @answer.question
  end

  def edit
    @answer = current_user.answers.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = current_user.answers.find(params[:id])
    @question = @answer.question

    if @answer.update(answer: params[:answer][:answer])
      redirect_to question_path(@question), notice: "Your answer has been updated"
    else
      render :edit
    end
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.build(answer: params[:answer][:answer], question_id: @question.id)

    if @answer.save
      redirect_to question_path(@question), notice: "Your answer has been recorded"
    else
      render :new
    end
  end

  def select_answer
    # users can only select answers for their own questions
    @question = current_user.questions.find(params[:question_id])
    @answer = @question.answers.find(params[:id])

    if @question.update(selected_answer_id: @answer.id)
      redirect_to question_path(@question), notice: "Your question has been marked as answered"
    else
      redirect_to question_path(@question), notice: "Sorry, something went wrong. Your answer could not be selected"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    if params[:search].present?
      @questions = Question.search(params[:search])
    else
      @questions = Question.all
    end
  end

  def answered
    @questions = Question.answered

    render :index
  end

  def new
    @question = Question.new
    3.times.map {@question.question_tags.build(color: "#FEC30A")}
  end

  def edit
    @question = current_user.questions.find(params[:id])
    @question.question_tags.build(color: "#FEC30A")
  end

  def update
    @question = current_user.questions.find(params[:id])

    if @question.update(permitted_question_params)
      redirect_to question_path(@question), notice: "Your question has been updated"
    else
      render :edit
    end
  end

  def create
    @question = current_user.questions.build(permitted_question_params)

    if @question.save
      redirect_to question_path(@question), notice: "Your question has been submitted"
    else
      (3 - @question.question_tags.size).times.map {@question.question_tags.build(color: "#FEC30A")}
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def destroy
    question = current_user.questions.find(params[:id])

      if question.destroy
        redirect_to questions_path, notice: "Question has been deleted"
      else
        redirect_to question_path, notice: "Error"
      end
  end

  private

  def permitted_question_params
    params.require(:question).permit(:content, :summary, :tag_names, question_tags_attributes: [:name, :color])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    render json: Tag.all
  end

  def create
    if params[:question_id]
      question = current_user.questions.find(params[:question_id])
      tag = Tag.find_or_initialize_by(name: params[:name])
      question.tags << tag
      render json: tag
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.json {render json: @user}
      format.html {}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def colored_tags(question_tags)
    if question_tags.any?
      content_tag(:small, class: "question-tags") do
        "Tags: ".html_safe +
        question_tags.map do |qt|
          content_tag(:span, qt.name, style: "color: #{qt.color}")
        end.join(', ').html_safe
      end
    else
      content_tag(:small, "", class: "question-tags")
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div class="card">
  <div class="card-body">
    <div class="row align-items-center">
      <% if answer.question.selected_answer == answer %>
        <div class="col select-answer selected-answer">
          &#x2705;
        </div>
      <% else %>
        <div class="col select-answer">
          <%= link_to "&#x2705;".html_safe, select_answer_question_answer_path(answer.question, answer), method: :patch, title: "green check marks best answer" if answer.question.user == current_user %>
        </div>
      <% end %>
      <div class="col-11">
        <%= answer.answer %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <small class="text-muted">
      Answered by <%= link_to answer.user.full_name, user_path(answer.user) %>,
      <%= content_tag(:abbr, title: answer.created_at) do %>
        <%= time_ago_in_words(answer.created_at) %> ago
      <% end %>
    </small>
    <small><%= link_to  "Edit", edit_question_answer_path(answer.question, answer) if answer.user == current_user %></small>
  </div>
</div>

app/views/answers/_form.html.erb
<% if @answer.errors.any? %>
  <div class="alert alert-info" role="alert">
    <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@question, @answer] do |f| %>
  <div class="form-group">
    <%= f.label :answer %>
    <%= f.text_area :answer, class: "form-control", rows: 3 %>
  </div>
  <%= f.submit "Answer question", class: "btn btn-primary" %>
<% end %>

app/views/answers/index.html.erb
<div class="card-deck"><%= render @answers %></div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <%= link_to welcome_path, class: "navbar-brand" do %>
    <%= image_tag "thoughtful.png", alt: "Socratic" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <%= content_tag :li, class: "nav-item" + (current_page?(questions_path) && " active" || "") do %>
          <%= link_to "Questions", questions_path, class: "nav-link" %>
        <% end %>
        <li class="nav-item"><%= link_to current_user.full_name, user_path(current_user), class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Login with Google", user_google_oauth2_omniauth_authorize_path, class: "nav-link" %></li>
      <% end %>
    </ul>
    <% if current_user %>
      <%= form_tag questions_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
        <%= text_field_tag "search", params[:search], class: "form-control mr-sm-2", placeholder: "Search" %>
        <%= submit_tag "Search", class: "btn btn-outline-dark my-2 my-sm-0"%>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socratic</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="/logo.png" type="image/png">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main role="main" class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
  <div class="alert alert-info" role="alert">
    <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @question do |f| %>
  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: "form-control" %>
  </div>
  <datalist id="tag-list"></datalist>
  <%= f.fields_for :question_tags do |qtf| %>
    <div class="form-group">
      <span class="delete-tag">&#x2716;</span>
      <%= qtf.text_field :name, placeholder: "Tag Name", list: "tag-list", autocomplete: "off" %><%= qtf.text_field :color, placeholder: "Color", type: "color" %>
    </div>
  <% end %>
  <div class="form-group">
  </div>
  <div class="form-group">
    <%= f.label :content, "Question" %>
    <%= f.text_area :content, class: "form-control", rows: "3" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/questions/_question.html.erb
<div class="card my-2">
  <div class="card-body">
    <h5 class="card-title"><%= link_to question.summary, question_path(question) %></h5>
    <p class="card-question-text"><%= question.content %></p>
  </div>
  <div class="card-footer">
    <%= colored_tags(question.question_tags) %><% if current_page?(question_path(question)) && current_user == question.user %><span class="add-tag" data-question-id="<%=question.id%>">&#x2795;</span><% end %><br>
    <small class="text-muted">
      Asked by <%= link_to question.user.full_name, user_path(question.user), class: 'user-info-popover', data: {user_id: question.user.id} %>,
      <%= content_tag(:abbr, title: question.created_at) do %>
        <%= time_ago_in_words(question.created_at) %> ago
      <% end %>
    </small><br><hr>
    <small><%= link_to "New Answer", new_question_answer_path(question) %></small>
    <% if question.user == current_user %><small><%= link_to "Edit Question", edit_question_path(question) %> 
      <%= link_to "Delete Question", question_path(question), method: :delete %></small> <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<%= link_to "Ask a Question", new_question_path, class: "btn btn-primary" %>
<br>
<p>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "All", questions_path, class: "nav-link " + (current_page?(questions_path) && "active" || "") %>
    </li>
    <li class="nav-item">
      <%= link_to "Answered", answered_questions_path, class: "nav-link " + (current_page?(answered_questions_path) && "active" || "") %>
    </li>
  </ul>
</p>
<hr>
<div class="card-deck">
  <%= render @questions %>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<%= render @question %>

<hr>
<%= render 'answers/form' %>

<div class="answers"><%= render @question.answers %></div>

app/views/users/show.html.erb
<p class="lead"><%= @user.full_name %></p>
<%= image_tag @user.image_url, class: "img-thumbnail profile-image"%>
<p><%= link_to "Answers (#{@user.answers.count})", user_answers_path(@user) %></p>

app/views/welcome/welcome.html.erb
<% if current_user %>
  <%= image_tag current_user.image_url, class: "img-thumbnail profile-image" if current_user.image_url %><br>
  <p class="lead">Welcome to Socratic, <%= current_user.full_name %>. Looking good!</p>
<% else %>
  <p class="lead">Welcome to Socratic.</p>
<% end %>